# Generated by Django 3.0.14 on 2024-01-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unknown_faces/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
