# Generated by Django 3.0.14 on 2024-01-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unknownface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unknownface',
            old_name='date',
            new_name='timestamp',
        ),
    ]
